# ๐ค Dockerfile ููุจูุช ุงููุชูุฏู ุงููุถุงุฏ ููุญุธุฑ
FROM node:18-alpine

# ูุนูููุงุช ุงููุทูุฑ
LABEL maintainer="Advanced Bot Developer"
LABEL description="Advanced Anti-Ban AFK Bot for Minecraft Aternos Servers"
LABEL version="2.0.0"

# ุฅูุดุงุก ูุฌูุฏ ุงูุนูู
WORKDIR /app

# ูุณุฎ ูููุงุช ุงูุญุฒูุฉ
COPY package*.json ./

# ุชุซุจูุช ุงูุชุจุนูุงุช
RUN npm ci --only=production && \
    npm cache clean --force && \
    rm -rf /tmp/*

# ูุณุฎ ุงูููุฏ ุงููุตุฏุฑู
COPY . .

# ุฅูุดุงุก ูุณุชุฎุฏู ุบูุฑ ุฌุฐุฑ ููุฃูุงู
RUN addgroup -g 1001 -S botgroup && \
    adduser -S botuser -u 1001 -G botgroup

# ุชุบููุฑ ููููุฉ ุงููููุงุช
RUN chown -R botuser:botgroup /app

# ุงูุชุจุฏูู ูููุณุชุฎุฏู ุบูุฑ ุงูุฌุฐุฑ
USER botuser

# ูุชุญ ุงููููุฐ (ุงุฎุชูุงุฑู ูููุฑุงูุจุฉ)
EXPOSE 3000

# ูุชุบูุฑุงุช ุงูุจูุฆุฉ ุงูุงูุชุฑุงุถูุฉ
ENV NODE_ENV=production
ENV STEALTH_MODE=true
ENV PROTECTION_LEVEL=high
ENV DEBUG_MODE=false

# ูุญุต ุตุญุฉ ุงูุญุงููุฉ
HEALTHCHECK --interval=30s --timeout=10s --start-period=60s --retries=3 \
  CMD node -e "console.log('Bot is running')" || exit 1

# ุชุดุบูู ุงูุจูุช
CMD ["npm", "start"]
