# ๐ ููู ุชูููู Railway ููุจูุช ุงููุชูุฏู

[build]
builder = "nixpacks"

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

# ูุชุบูุฑุงุช ุงูุจูุฆุฉ ุงูุงูุชุฑุงุถูุฉ ูู Railway
[env]
NODE_ENV = "production"
STEALTH_MODE = "true"
PROTECTION_LEVEL = "high"
DEBUG_MODE = "false"
DAILY_REPORTS = "true"

# ุฅุนุฏุงุฏุงุช ุงูุตุญุฉ ูุงููุฑุงูุจุฉ
[healthcheck]
httpPath = "/"
httpPort = 3000
initialDelaySeconds = 60
intervalSeconds = 30
timeoutSeconds = 10

# ุฅุนุฏุงุฏุงุช ุงูุชูุณุน ุงูุชููุงุฆู
[autoscaling]
enabled = false
minInstances = 1
maxInstances = 1

# ุฅุนุฏุงุฏุงุช ุงูุดุจูุฉ
[networking]
allowPublic = false

# ุฅุนุฏุงุฏุงุช ุงูููุงุฑุฏ
[resources]
memoryGB = 0.5
vCPUs = 0.5

# ุฅุนุฏุงุฏุงุช ุงูุณุฌูุงุช
[logging]
level = "info"
format = "json"

# ุชููููุงุช ุฅุถุงููุฉ ูููุดุฑ
[railway]
# ุชูุนูู ุฅุนุงุฏุฉ ุงููุดุฑ ุงูุชููุงุฆู ุนูุฏ ุงูุชุญุฏูุซ
auto_deploy = true

# ูุฑุน Git ุงููุณุชุฎุฏู ูููุดุฑ
branch = "main"

# ูุชุบูุฑุงุช ุงูุจูุฆุฉ ุงููุทููุจุฉ (ูุฌุจ ุฅุถุงูุชูุง ูู ููุญุฉ Railway)
# SERVER_HOST=justforlaugh.aternos.me
# SERVER_PORT=19465
# BOT_USERNAME=AFKBot_JFL
# MC_VERSION=1.21.1
# BOT_AUTH=offline
